<a href="https://colab.research.google.com/github/harshitha020505/MLLab1/blob/main/MLLab146.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install scikit-learn

In [ ]:
import pandas as pd
series=pd.Series([chr(i) for i in range(65,65+27)])
print(series)

0     A
1     B
2     C
3     D
4     E
5     F
6     G
7     H
8     I
9     J
10    K
11    L
12    M
13    N
14    O
15    P
16    Q
17    R
18    S
19    T
20    U
21    V
22    W
23    X
24    Y
25    Z
26    [
dtype: object


In [ ]:
#9 create a dataframe
a=["Harshitha","Rasagna","sam","Rida","jahnavi"]
data={
    2014:[100,101,102,103,104],
    2015:[200,201,203,204,205],
    2016:[300,301,302,303,304],
    2017:[400,401,402,403,404]
}
df=pd.DataFrame(data,index=a)
print(df)

           2014  2015  2016  2017
Harshitha   100   200   300   400
Rasagna     101   201   301   401
sam         102   203   302   402
Rida        103   204   303   403
jahnavi     104   205   304   404


In [ ]:
#10
#a
print(df.index)#row labels
#b
print(df.columns)# column labels
#c
print(df.dtypes)#datatypes of each column
#d
print(df.ndim) #to display the dimensions of the dataframe
print(df.shape) # to get the shape of the dataframe
print(df.size) # to get the size of the dataframe
print(df.values) # to  get the values of the dataframe
#e
print(df.tail(2))# to display the last two rows of a dataframe
#f
print(df.head(2)) # to display the first two rows of a dataframe



Index(['Harshitha', 'Rasagna', 'sam', 'Rida', 'jahnavi'], dtype='object')
Index([2014, 2015, 2016, 2017], dtype='int64')
2014    int64
2015    int64
2016    int64
2017    int64
dtype: object
2
(5, 4)
20
[[100 200 300 400]
 [101 201 301 401]
 [102 203 302 402]
 [103 204 303 403]
 [104 205 304 404]]
         2014  2015  2016  2017
Rida      103   204   303   403
jahnavi   104   205   304   404
           2014  2015  2016  2017
Harshitha   100   200   300   400
Rasagna     101   201   301   401


In [ ]:
#10
#g
import pandas as pd
data = {
    "Harshitha": 160000,
    "Rasagna": 110000,
    "sam": 500000,
    "Rida": 340000,
    "jahnavi": 900000
}
Sales2 = pd.DataFrame.from_dict(data, orient='index',columns=['2018'])

print(Sales2)
#h
print(df.empty)


             2018
Harshitha  160000
Rasagna    110000
sam        500000
Rida       340000
jahnavi    900000
False


In [ ]:
#11
#a
df[2018]=Sales2['2018']
print(df)
#b
print(df.T)
#c
print(df[2017])
#d
result=df.loc[["Harshitha","jahnavi"],[2017,2018]]
print(result)
#e
r=df.loc["sam",2016]
print(r)
#f
sumeet = [196.2, 37800, 52000, 78438, 38852]
years = [2014, 2015, 2016, 2017, 2018]
df.loc["Sumeet"] = pd.Series(data=sumeet, index=years)
print(df)
#g
df1=df.drop(2014,axis=1)
print(df1)
#h
df2=df.drop("sam",axis=0)
print(df2)
#i
df3=df.rename(index={
    "Rasagna":"vivaan",
    "jahnavi":"shailesh"
},inplace=False)
print(df3)
#j
df3.loc["shailesh", 2018] = 100000
print(df3.loc["shailesh"])
#k
df3.to_csv("SalesFigures.csv", index=False, header=False)
#l
SalesRetrieved = pd.read_csv("SalesFigures.csv", header=None)
SalesRetrieved.index = df3.index
SalesRetrieved.columns = df3.columns
print(SalesRetrieved)



            2014     2015     2016     2017      2018
Harshitha  100.0    200.0    300.0    400.0  160000.0
Rasagna    101.0    201.0    301.0    401.0  110000.0
sam        102.0    203.0    302.0    402.0  500000.0
Rida       103.0    204.0    303.0    403.0  340000.0
jahnavi    104.0    205.0    304.0    404.0  900000.0
Sumeet     196.2  37800.0  52000.0  78438.0       NaN
      Harshitha   Rasagna       sam      Rida   jahnavi   Sumeet
2014      100.0     101.0     102.0     103.0     104.0    196.2
2015      200.0     201.0     203.0     204.0     205.0  37800.0
2016      300.0     301.0     302.0     303.0     304.0  52000.0
2017      400.0     401.0     402.0     403.0     404.0  78438.0
2018   160000.0  110000.0  500000.0  340000.0  900000.0      NaN
Harshitha      400.0
Rasagna        401.0
sam            402.0
Rida           403.0
jahnavi        404.0
Sumeet       78438.0
Name: 2017, dtype: float64
            2017      2018
Harshitha  400.0  160000.0
jahnavi    404.0  900000.

In [ ]:
#13
#a
data = {
    "Item": ["TV", "TV", "TV", "AC"],
    "Company": ["LG", "VIDEOCON", "LG", "SONY"],
    "Rupees": [12000, 10000, 15000, 14000],
    "USD": [700, 650, 800, 750]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)
#b
new_rows = pd.DataFrame([
    {"Item": "TV", "Company": "SAMSUNG", "Rupees": 13000, "USD": 720},
    {"Item": "AC", "Company": "SONY", "Rupees": 16000, "USD": 790}
])
df = pd.concat([df, new_rows], ignore_index=True)
print(df)
#c
a=df[(df["Item"]=="TV") & (df["Company"]=="LG")]["Rupees"].max()
print(a)
#d
b=df["Rupees"].sum()
print(b)
#e
c=df[df["Company"]=="SONY"]["USD"].median()
print(c)
#f
df_sorted = df.sort_values(by="Rupees")
print(df_sorted)

Original DataFrame:
  Item   Company  Rupees  USD
0   TV        LG   12000  700
1   TV  VIDEOCON   10000  650
2   TV        LG   15000  800
3   AC      SONY   14000  750
  Item   Company  Rupees  USD
0   TV        LG   12000  700
1   TV  VIDEOCON   10000  650
2   TV        LG   15000  800
3   AC      SONY   14000  750
4   TV   SAMSUNG   13000  720
5   AC      SONY   16000  790
15000
80000
770.0
  Item   Company  Rupees  USD
1   TV  VIDEOCON   10000  650
0   TV        LG   12000  700
4   TV   SAMSUNG   13000  720
3   AC      SONY   14000  750
2   TV        LG   15000  800
5   AC      SONY   16000  790


In [ ]:
#14
#a
import numpy as np
data = {
    'Name': ['Alice', 'Bob', 'Carol', 'David', 'Eve'],
    'Degree': ['BCA', 'BCA', 'MBA', 'MBA', 'BCA'],
    'Marks': [85, np.nan, 90, 80, 88]
}

df5 = pd.DataFrame(data)
#b
print(df5.groupby("Degree")["Marks"].max())
#c
df5["Marks"] = df5["Marks"].fillna(76)
#d
df5.set_index('Name', inplace=True)
#e
print(df5.groupby(["Name", "Degree"])["Marks"].mean())
#f
print((df5["Degree"] == "MBA").sum())
#g
print(df5[df5["Degree"] == "BCA"]["Marks"].mode())


Degree
BCA    88.0
MBA    90.0
Name: Marks, dtype: float64
Name   Degree
Alice  BCA       85.0
Bob    BCA       76.0
Carol  MBA       90.0
David  MBA       80.0
Eve    BCA       88.0
Name: Marks, dtype: float64
2
0    76.0
1    85.0
2    88.0
Name: Marks, dtype: float64


In [ ]:
#Solved Case Study based on Open Datasets
#1
import pandas as pd
columns = ['mpg', 'cylinders', 'displacement', 'horsepower',
           'weight', 'acceleration', 'model_year', 'origin', 'car_name']
autodf = pd.read_csv('auto-mpg.data', delim_whitespace=True, names=columns, na_values='?')
#2
print(autodf.describe(include='all'))
#3
print(autodf.head(10))
#4
autodf_filled = autodf.fillna(method='ffill')
print(autodf_filled)
autodf_cleaned = autodf.dropna()
print(autodf_cleaned)
#5
max_mpg = autodf_cleaned['mpg'].max()
max_mpg_car = autodf_cleaned[autodf_cleaned['mpg'] == max_mpg]
print(max_mpg_car[['car_name', 'mpg']])
#6
avg_displacement = autodf_cleaned.groupby('cylinders')['displacement'].mean()
print(avg_displacement)
#7
avg_cylinders = autodf_cleaned['cylinders'].mean()
print(avg_cylinders)
#8
average_weight = autodf_cleaned['weight'].mean()
count_heavy_cars = autodf_cleaned[autodf_cleaned['weight'] > average_weight].shape[0]
print(count_heavy_cars)


               mpg   cylinders  displacement  horsepower       weight  \
count   398.000000  398.000000    398.000000  392.000000   398.000000   
unique         NaN         NaN           NaN         NaN          NaN   
top            NaN         NaN           NaN         NaN          NaN   
freq           NaN         NaN           NaN         NaN          NaN   
mean     23.514573    5.454774    193.425879  104.469388  2970.424623   
std       7.815984    1.701004    104.269838   38.491160   846.841774   
min       9.000000    3.000000     68.000000   46.000000  1613.000000   
25%      17.500000    4.000000    104.250000   75.000000  2223.750000   
50%      23.000000    4.000000    148.500000   93.500000  2803.500000   
75%      29.000000    8.000000    262.000000  126.000000  3608.000000   
max      46.600000    8.000000    455.000000  230.000000  5140.000000   

        acceleration  model_year      origin    car_name  
count     398.000000  398.000000  398.000000         398  
uniqu

/tmp/ipython-input-63-1697215883.py:4: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  autodf = pd.read_csv('auto-mpg.data', delim_whitespace=True, names=columns, na_values='?')
/tmp/ipython-input-63-1697215883.py:10: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  autodf_filled = autodf.fillna(method='ffill')
